#!/bin/bash -x

# Airband channels: aprox. of SBFL and SBJV/SBNF
FREQS="119650000 119500000"
CHANNEL_BW=10000

# Determine center automatically
s=0
n=0
for f in $FREQS; do
	s=$(($s + $f))
	n=$(($n + 1))
done
STEP=2500
CENTR=$(($s / $n))
CENTR=$(($CENTR / $STEP))
CENTR=$(($CENTR * $STEP))
# CENTR=119400000

BW=1000000
# Note: AM does not work well with autocorrelation squelch
rtl_sdr -f $CENTR -g 43 -s $BW - | ./nfm.py $CENTR $BW $STEP $CHANNEL_BW $FREQS . --am $*
