#!/bin/sh -x
# Decode digital radio (DMR et al.) and save audio as WAV
# using rtl_fm as front-end

if [ "$1" = "" ]; then
	FREQ="162656000"
else
	FREQ="$1"
fi
RTLFM="rtl_fm -M fm -f $FREQ -p 0 -g 25 -s 48000 -"
$RTLFM | dsd -i - -w ${FREQ}.wav -pe -pl -ps -pt
