#!/bin/sh -x

# Record and decode 10 seconds of broadcast FM.
# Outputs mono, unfiltered audio.

rtl_sdr -f 93.1M -s 256k -n 2560000 teste.iq
cat teste.iq | ./fm1.py > teste.raw
sox -t raw -r 256000 -b 16 -c 1 -L -e signed-integer teste.raw -d rate 32000
