#!/bin/bash -x

# Record narrow FM channels (most commonly VHF and UHF) as audio WAV files

FREQS="858612500 858888750 859112500 859462500"
# FREQS="858612500"

# Determine center automatically
s=0
n=0
for f in $FREQS; do
	s=$(($s + $f))
	n=$(($n + 1))
done
STEP=1250
CENTR=$(($s / $n - 20000))
CENTR=$(($CENTR / $STEP))
CENTR=$(($CENTR * $STEP))

BW=1250000
CHANNEL_BW=10000

rtl_sdr -f $CENTR -p 2 -g 49 -s $BW - | ./nfm.py $CENTR $BW $STEP $CHANNEL_BW $FREQS . -a -e
