#!/bin/sh -x

RATE=22050
RTLFM="rtl_fm -M fm -f 145.570M -p 72 -g 49 -s $RATE -"
PLAY="play -r $RATE -t raw -e s -b 16 -c 1 -V1 -"
DIREWOLF="direwolf -c sdr-1200bps.conf -r $RATE -D 1 -B 1200 -t 0 -"
MULTIMON="multimon-ng -t raw -A -"

# $RTLFM | $PLAY
$RTLFM | parallel --pipe --tee {} ::: "$PLAY" "$DIREWOLF"
